CREATE TABLE user (
    User_id	INTEGER PRIMARY KEY,
    FName	TEXT NOT NULL,
    LName	TEXT NOT NULL,
    Added	TEXT NOT NULL,
    Role	TEXT NOT NULL,
    AccName	TEXT NOT NULL,
    Passwd	TEXT NOT NULL
);
